[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py38"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0411",  # Wrong import order (isort will handle this)
]

[tool.pylint.format]
max-line-length = 120